FROM debian

MAINTAINER yoshihiroxx

RUN echo "now building..."

RUN apt-get update
# RUN apt-get -y install build-essential
RUN apt-get -y install autotools-dev autoconf automake libtool libudev-dev libusb-1.0-0-dev libfox-1.6-dev build-essential clang

WORKDIR /home/
